import type { Metadata } from "next";
import { Poppins, Urbanist } from "next/font/google";
import clsx from "clsx";

import "./globals.css";
import styles from "./page.module.scss";
import Navbar from "@/components/Navbar/Navbar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const poppins = Poppins({
  weight: ["100", "200", "300", "400", "500", "600", "700"],
  subsets: ["latin"],
  variable: "--font-poppins",
});

const urbanist = Urbanist({
  subsets: ["latin"],
  variable: "--font-urbanist",
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={clsx(poppins.variable, urbanist.variable, "font-sans")}>
        <Navbar />

        <main className={styles["main"]}>{children}</main>
      </body>
    </html>
  );
}
